<a href="https://colab.research.google.com/github/RevazRevazashvili/DataScience_learning/blob/main/titanic_survivors_using_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np

In [22]:
raw_data = pd.read_csv('train.csv')

In [23]:
raw_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [27]:
raw_data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
nans = np.where(raw_data.Age.isna())[0]
for i in nans:
  raw_data.Age[i] = raw_data.Age.mean()

In [29]:
print(f"{round(raw_data.Age.isna().sum()/raw_data.shape[0] * 100.0, 2)}% missing age data")

0.0% missing age data


In [30]:
raw_data['Sex'] = raw_data['Sex'].astype('category')
raw_data['Sex'] = raw_data['Sex'].cat.codes
raw_data['Ticket'] = raw_data['Ticket'].astype('category')
raw_data['Ticket'] = raw_data['Ticket'].cat.codes
raw_data['Cabin'] = raw_data['Cabin'].astype('category')
raw_data['Cabin'] = raw_data['Cabin'].cat.codes
raw_data['Embarked'] = raw_data['Embarked'].astype('category')
raw_data['Embarked'] = raw_data['Embarked'].cat.codes

In [31]:
raw_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

   Ticket     Fare  Cabin  Embarked  
0     523   7.2500     -1         2  
1     596  71.2833     81         0  
2     669   7.9250     -1         2  
3      49  53.1000     55         2  
4     472   8.0500     -1         2

In [67]:
col = ['Name', 'PassengerId', 'Ticket', 'Survived', 'Cabin']
X = raw_data.drop(columns=col)
X

Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0         3    1  22.000000      1      0   7.2500         2
1         1    0  38.000000      1      0  71.2833         0
2         3    0  26.000000      0      0   7.9250         2
3         1    0  35.000000      1      0  53.1000         2
4         3    1  35.000000      0      0   8.0500         2
..      ...  ...        ...    ...    ...      ...       ...
886       2    1  27.000000      0      0  13.0000         2
887       1    0  19.000000      0      0  30.0000         2
888       3    0  29.699118      1      2  23.4500         2
889       1    1  26.000000      0      0  30.0000         0
890       3    1  32.000000      0      0   7.7500         1

[891 rows x 7 columns]

In [68]:
y = raw_data['Survived']
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=21)

In [71]:
X_train

Pclass  Sex        Age  SibSp  Parch      Fare  Embarked
241       3    0  29.699118      1      0   15.5000         1
734       2    1  23.000000      0      0   13.0000         2
581       1    0  39.000000      1      1  110.8833         0
456       1    1  65.000000      0      0   26.5500         2
118       1    1  24.000000      0      1  247.5208         0
..      ...  ...        ...    ...    ...       ...       ...
368       3    0  29.699118      0      0    7.7500         1
48        3    1  29.699118      2      0   21.6792         0
772       2    0  57.000000      0      0   10.5000         2
824       3    1   2.000000      4      1   39.6875         2
207       3    1  26.000000      0      0   18.7875         0

[623 rows x 7 columns]

In [72]:
X_test

Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
617       3    0  26.000000      1      0  16.1000         2
379       3    1  19.000000      0      0   7.7750         2
725       3    1  20.000000      0      0   8.6625         2
826       3    1  29.699118      0      0  56.4958         2
450       2    1  36.000000      1      2  27.7500         2
..      ...  ...        ...    ...    ...      ...       ...
394       3    0  24.000000      0      2  16.7000         2
463       2    1  48.000000      0      0  13.0000         2
13        3    1  39.000000      1      5  31.2750         2
12        3    1  20.000000      0      0   8.0500         2
649       3    0  23.000000      0      0   7.5500         2

[268 rows x 7 columns]

In [73]:
from sklearn.preprocessing import StandardScaler

In [74]:
scaler = StandardScaler()

In [75]:
X_train_scaled = scaler.fit_transform(X_train)

In [76]:
X_test_scaled = scaler.transform(X_test)

In [77]:
X_train_scaled

array([[ 0.82164988, -1.38246698, -0.00518896, ..., -0.44975733,
        -0.337763  , -0.69441558],
       [-0.38563285,  0.72334458, -0.51489946, ..., -0.44975733,
        -0.39030024,  0.58175228],
       [-1.59291557, -1.38246698,  0.70247996, ...,  0.85349298,
         1.66670707, -1.97058343],
       ...,
       [-0.38563285, -1.38246698,  2.07203181, ..., -0.44975733,
        -0.44283748,  0.58175228],
       [ 0.82164988,  0.72334458, -2.11270995, ...,  0.85349298,
         0.17053478,  0.58175228],
       [ 0.82164988,  0.72334458, -0.28664082, ..., -0.44975733,
        -0.26867653, -1.97058343]])

In [78]:
X_test_scaled

array([[ 0.82164988, -1.38246698, -0.28664082, ..., -0.44975733,
        -0.32515406,  0.58175228],
       [ 0.82164988,  0.72334458, -0.81924432, ..., -0.44975733,
        -0.50010307,  0.58175228],
       [ 0.82164988,  0.72334458, -0.7431581 , ..., -0.44975733,
        -0.48145235,  0.58175228],
       ...,
       [ 0.82164988,  0.72334458,  0.70247996, ...,  6.06649426,
        -0.00625303,  0.58175228],
       [ 0.82164988,  0.72334458, -0.7431581 , ..., -0.44975733,
        -0.49432397,  0.58175228],
       [ 0.82164988, -1.38246698, -0.51489946, ..., -0.44975733,
        -0.50483142,  0.58175228]])

In [79]:
from sklearn.linear_model import LogisticRegression

In [80]:
log_reg = LogisticRegression(random_state=0).fit(X_train_scaled, y_train)

In [ ]:
log_reg.predict(X_train_scaled)

In [82]:
log_reg.score(X_train_scaled, y_train)

0.8025682182985554

In [83]:
log_reg.score(X_test_scaled, y_test)

0.8097014925373134

In [84]:
log_reg1 = LogisticRegression(random_state=0,
                              C = 0.01,
                              fit_intercept = True,
                              ).fit(X_train_scaled, y_train)

In [ ]:
log_reg1.predict(X_train_scaled)

In [86]:
log_reg1.score(X_train_scaled, y_train)

0.812199036918138

In [87]:
log_reg1.score(X_test_scaled, y_test)

0.8134328358208955

In [62]:
test_data = pd.read_csv('test.csv')

In [89]:
test_data.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [66]:
test_data.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
test_data.dropna()

In [117]:
nans1 = np.where(test_data.Age.isna())[0]
for i in nans1:
  test_data.Age[i] = test_data.Age.mean()

<ipython-input-117-cbf4ae0b3837>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data.Age[i] = test_data.Age.mean()


In [118]:
test_data.head()

PassengerId  Pclass                                          Name  Sex  \
0          892       3                              Kelly, Mr. James    1   
1          893       3              Wilkes, Mrs. James (Ellen Needs)    0   
2          894       2                     Myles, Mr. Thomas Francis    1   
3          895       3                              Wirz, Mr. Albert    1   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    0   

    Age  SibSp  Parch   Ticket     Fare Cabin  Embarked  
0  34.5      0      0   330911   7.8292   NaN         1  
1  47.0      1      0   363272   7.0000   NaN         2  
2  62.0      0      0   240276   9.6875   NaN         1  
3  27.0      0      0   315154   8.6625   NaN         2  
4  22.0      1      1  3101298  12.2875   NaN         2

In [119]:
test_data['Sex'] = test_data['Sex'].astype('category')
test_data['Sex'] = test_data['Sex'].cat.codes
test_data['Embarked'] = test_data['Embarked'].astype('category')
test_data['Embarked'] = test_data['Embarked'].cat.codes

In [120]:
col = ['Name', 'PassengerId', 'Ticket', 'Cabin']
XT = test_data.drop(columns=col)
XT

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0         3    1  34.50000      0      0    7.8292         1
1         3    0  47.00000      1      0    7.0000         2
2         2    1  62.00000      0      0    9.6875         1
3         3    1  27.00000      0      0    8.6625         2
4         3    0  22.00000      1      1   12.2875         2
..      ...  ...       ...    ...    ...       ...       ...
413       3    1  30.27259      0      0    8.0500         2
414       1    0  39.00000      0      0  108.9000         0
415       3    1  38.50000      0      0    7.2500         2
416       3    1  30.27259      0      0    8.0500         2
417       3    1  30.27259      1      1   22.3583         0

[418 rows x 7 columns]

In [127]:
XT.isna().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [126]:
XT.dropna(inplace=True)

In [128]:
X_test_scaled1 = scaler.transform(XT)

In [129]:
X_test_scaled1

array([[ 0.82164988,  0.72334458,  0.360092  , ..., -0.44975733,
        -0.49896406, -0.69441558],
       [ 0.82164988, -1.38246698,  1.31116967, ..., -0.44975733,
        -0.51638961,  0.58175228],
       [-0.38563285,  0.72334458,  2.45246288, ..., -0.44975733,
        -0.45991208, -0.69441558],
       ...,
       [ 0.82164988,  0.72334458,  0.66443685, ..., -0.44975733,
        -0.51113589,  0.58175228],
       [ 0.82164988,  0.72334458,  0.0384444 , ..., -0.44975733,
        -0.49432397,  0.58175228],
       [ 0.82164988,  0.72334458,  0.0384444 , ...,  0.85349298,
        -0.19363655, -1.97058343]])

In [134]:
predictions = log_reg.predict(X_test_scaled1)

In [135]:
predictions_data = pd.DataFrame(predictions, columns=['Survived'])

In [137]:
predictions_data

Survived
0           0
1           0
2           0
3           0
4           1
..        ...
412         0
413         1
414         0
415         0
416         0

[417 rows x 1 columns]